[build]
builder = "nixpacks"
watchPatterns = ["**/*.py", "**/*.json", "**/*.toml", "requirements.txt"]

[deploy]
startCommand = "python start_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
