[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn api.app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.watchPatterns]
include = ["**/*.py", "**/*.json", "**/*.toml", "requirements.txt"]
ignore = ["**/__pycache__/**", "**/.git/**", "**/node_modules/**"]
